import './app'
import './commonStyle/common.css'
import './commonStyle/buttons.css'
import './components/forms/sendForm.css'
import './components/forms/sendTextForm.css'
import './components/forms/sendFileForm.css'
import './components/contentView/contentView.css'
import './components/message/message.css'
import './components/changeDateMessage/changeDateMessage.css'
import './components/navigator/navigator.css'
import './components/messageOptions/messageOptions.css'
import './components/contentMessage/contentMessage.css'
import './components/pinMMessage/pinMessage.css'
import './components/forms/searchForm.css'

